name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - os: macos-latest
            python: 3.7
          - os: macos-latest
            python: 3.12
          - os: windows-2022
            python: 3.7
          - os: windows-2022
            python: 3.12

    steps:
      - uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade --pre -r dev-requirements.txt .
      
      - name: show environment
        run: |
          pip freeze

      - name: Run tests
        run: |
          pytest -v --color=yes --cov=wurlitzer tests
